version: "3.9"
services:
  rabbitmq-management:
    image: "rabbitmq:management"
    # 容器名称
    container_name: rabbitmq-management
    # 端口号
    ports:
      - 15672:15672
      - 5672:5672
    # 容器内部参数
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    # 挂载数据卷
    volumes:
      - /home/docker/rabbitmq-management/data:/var/lib/rabbitmq
    # 容器意外关闭进行重启操作
    restart: always 