version: "3.9"
services:
  mysql:
    image: "mysql:latest"
    # 容器名称
    container_name: mysql
    # 端口号
    ports:
      - 3306:3306
    # 容器内部参数
    environment:
      MYSQL_ROOT_PASSWORD: "Xiaolei@520.com"
      AllowPublicKeyRetrieval: "true"
    # 容器意外关闭进行重启操作
    restart: always 